// Generated by Wrangler on Sun Sep 08 2024 13:47:09 GMT+0800 (中国标准时间)
// by running `wrangler types`

interface Env {
	KV: KVNamespace;
	MEDIA_BUCKET_PUBLIC_URL: "/media";
	MEDIA_BUCKET: R2Bucket;
	DB: D1Database;
}
